<a href="https://colab.research.google.com/github/ArincDemirel/PyTorch--Deep-Learning-Projects/blob/main/00_PyTorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/


In [10]:
!nvidia-smi

Fri Oct 20 23:28:19 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   46C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
torch.__version__

'2.1.0+cu118'

In [7]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [8]:
scalar.ndim

0

In [9]:
scalar.item()

7

In [13]:
#Vector
vector = torch.tensor([[7,7],[8,8]])
vector

tensor([[7, 7],
        [8, 8]])

In [14]:
vector.shape

torch.Size([2, 2])

In [30]:
TENSOR = torch.randn(5,3,3)
TENSOR

tensor([[[-0.2999,  0.2903, -0.8210],
         [ 0.6895, -0.9713,  0.2812],
         [-1.4786, -0.2323,  0.5117]],

        [[ 0.4264, -0.2932,  0.0433],
         [ 1.0519,  0.7822,  0.6461],
         [-0.3248, -1.0319,  1.1624]],

        [[-1.8643, -0.3610,  2.1357],
         [-2.6604,  0.0388,  1.0986],
         [-0.5601,  0.3619, -1.8925]],

        [[-0.7837,  0.1371,  0.1747],
         [ 0.9004, -0.7141, -1.5575],
         [ 0.3151,  1.7755, -2.4244]],

        [[ 1.1097,  0.0878, -0.1313],
         [-1.7486,  0.5281, -2.1593],
         [-0.9689,  0.9445, -0.3031]]])

In [18]:
 TENSOR.ndim

3

In [21]:
TENSOR.shape

torch.Size([3, 3, 3])

In [22]:
TENSOR[0]

tensor([[ 1.2247,  0.5925, -1.7879],
        [ 1.2199,  0.1643,  1.4434],
        [ 0.9675,  0.3975, -0.8417]])

Random tensors are impirtant because the way many neural networks is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [27]:
#Create a random tensor with similar shape of an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor

tensor([[[0.4630, 0.4717, 0.6500,  ..., 0.1944, 0.3641, 0.3685],
         [0.2574, 0.4990, 0.6938,  ..., 0.7154, 0.2949, 0.9840],
         [0.7226, 0.7401, 0.8292,  ..., 0.5368, 0.2265, 0.3208],
         ...,
         [0.8417, 0.4966, 0.2350,  ..., 0.3101, 0.8437, 0.3572],
         [0.8017, 0.8010, 0.8204,  ..., 0.1090, 0.8569, 0.9033],
         [0.8982, 0.3633, 0.8538,  ..., 0.6086, 0.9509, 0.4611]],

        [[0.1369, 0.3411, 0.2016,  ..., 0.4300, 0.8250, 0.8902],
         [0.5090, 0.2491, 0.1640,  ..., 0.9514, 0.8861, 0.1429],
         [0.9724, 0.0376, 0.6459,  ..., 0.9747, 0.0149, 0.2987],
         ...,
         [0.7651, 0.5812, 0.7557,  ..., 0.6079, 0.8849, 0.5301],
         [0.4349, 0.7584, 0.5751,  ..., 0.4236, 0.6739, 0.7968],
         [0.7675, 0.6074, 0.4942,  ..., 0.1429, 0.8729, 0.1870]],

        [[0.1083, 0.0359, 0.2821,  ..., 0.6571, 0.8326, 0.3429],
         [0.0108, 0.2131, 0.2254,  ..., 0.1816, 0.5205, 0.6002],
         [0.4893, 0.1686, 0.2868,  ..., 0.3675, 0.4750, 0.

In [28]:
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [36]:
one_to_ten = torch.arange(0,10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [48]:
TNSR1 = torch.tensor([3.0, 6.0, 9.0], dtype = float , #float16 / float32
                                     device = "cpu", # or 'cuda'
                                      requires_grad = False ) # to track gradient if tensor goes through certain numerical calculations

In [49]:
TNSR1

tensor([3., 6., 9.], dtype=torch.float64)

In [50]:
TNSR2 = torch.tensor([3.0, 6.0, 9.0], dtype = torch.float16 , #float16 / float32
                                     device = "cpu", # or 'cuda'
                                      requires_grad = False ) # to track gradient if tensor goes through certain numerical calculations

In [51]:
TNSR2

tensor([3., 6., 9.], dtype=torch.float16)