<a href="https://colab.research.google.com/github/ArincDemirel/PyTorch--Deep-Learning-Projects/blob/main/00_PyTorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
torch.__version__

'2.1.0+cu118'

In [5]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [8]:
#Vector
vector = torch.tensor([[7,7],[8,8]])
vector

tensor([[7, 7],
        [8, 8]])

In [9]:
vector.shape

torch.Size([2, 2])

In [10]:
TENSOR = torch.randn(5,3,3)
TENSOR

tensor([[[-1.1873, -0.0605,  0.3854],
         [-2.1014,  0.5827,  0.8315],
         [-0.8998, -0.8992,  1.9852]],

        [[-0.5056, -0.1917, -1.5142],
         [-0.9752, -1.0850, -0.9616],
         [-1.1416, -0.0299, -1.0793]],

        [[-0.6902,  0.5870,  1.9430],
         [-0.4831,  0.4563, -0.4271],
         [ 0.6381, -0.1214, -2.9605]],

        [[-0.6427,  1.5029,  2.4200],
         [ 1.5435,  0.5820,  0.2056],
         [-0.0325, -1.1968,  0.5654]],

        [[ 0.2050, -1.8322,  1.2125],
         [-0.6267,  1.2677, -0.4363],
         [ 0.8381,  0.3106, -0.7365]]])

In [11]:
 TENSOR.ndim

3

In [12]:
TENSOR.shape

torch.Size([5, 3, 3])

In [13]:
TENSOR[0]

tensor([[-1.1873, -0.0605,  0.3854],
        [-2.1014,  0.5827,  0.8315],
        [-0.8998, -0.8992,  1.9852]])

Random tensors are impirtant because the way many neural networks is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [14]:
#Create a random tensor with similar shape of an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor

tensor([[[0.3573, 0.7891, 0.0869,  ..., 0.8994, 0.9065, 0.5901],
         [0.3996, 0.7577, 0.1504,  ..., 0.8052, 0.2589, 0.3595],
         [0.9225, 0.1171, 0.6564,  ..., 0.2645, 0.0688, 0.0757],
         ...,
         [0.0886, 0.2736, 0.4990,  ..., 0.0178, 0.3220, 0.1320],
         [0.1509, 0.5974, 0.7688,  ..., 0.0931, 0.5204, 0.2756],
         [0.7717, 0.7840, 0.8128,  ..., 0.3082, 0.7809, 0.6573]],

        [[0.8629, 0.4960, 0.6945,  ..., 0.3917, 0.8004, 0.5743],
         [0.4225, 0.5299, 0.3517,  ..., 0.3837, 0.8937, 0.9681],
         [0.0123, 0.5557, 0.9604,  ..., 0.1741, 0.2304, 0.3921],
         ...,
         [0.1890, 0.0688, 0.4464,  ..., 0.2072, 0.7057, 0.2761],
         [0.4434, 0.3425, 0.3060,  ..., 0.3737, 0.0125, 0.2547],
         [0.6718, 0.7512, 0.9738,  ..., 0.2462, 0.5184, 0.5426]],

        [[0.6133, 0.4614, 0.5835,  ..., 0.1070, 0.1033, 0.9195],
         [0.6773, 0.8509, 0.5568,  ..., 0.0465, 0.1987, 0.6519],
         [0.0418, 0.6618, 0.9055,  ..., 0.6082, 0.7775, 0.

In [15]:
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [16]:
one_to_ten = torch.arange(0,10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
TNSR1 = torch.tensor([3.0, 6.0, 9.0], dtype = float , #float16 / float32
                                     device = "cpu", # or 'cuda'
                                      requires_grad = False ) # to track gradient if tensor goes through certain numerical calculations

In [19]:
TNSR1

tensor([3., 6., 9.], dtype=torch.float64)

In [42]:
TNSR2_float16 = torch.tensor([5.0, 2.0, 11.0], dtype = torch.float16 , #float16 / float32
                                     device = "cpu", # or 'cuda'
                                      requires_grad = False ) # to track gradient if tensor goes through certain numerical calculations

In [26]:
TNSR2_float16

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
int_32_tensor = torch.tensor([3.0, 6.0, 9.0])
int_32_tensor

tensor([3., 6., 9.])

In [28]:
TNSR2_float16 * int_32_tensor

tensor([ 9., 36., 81.])

In [31]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9336, 0.0371, 0.8879, 0.8898],
        [0.7268, 0.3451, 0.5851, 0.5552],
        [0.5358, 0.5650, 0.0554, 0.8095]])

In [35]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Datatype of tensor:{some_tensor.shape}")
print(f"Datatype of tensor:{some_tensor.device}")

tensor([[0.9336, 0.0371, 0.8879, 0.8898],
        [0.7268, 0.3451, 0.5851, 0.5552],
        [0.5358, 0.5650, 0.0554, 0.8095]])
Datatype of tensor:torch.float32
Datatype of tensor:torch.Size([3, 4])
Datatype of tensor:cpu


## Matrix Multiplication
1. Element- Wise
2. Dot product

In [45]:
## 1
tnsr_mul = TNSR2_float16 * int_32_tensor
print(TNSR2_float16)
print(int_32_tensor)
print(tnsr_mul)


tensor([ 5.,  2., 11.], dtype=torch.float16)
tensor([3., 6., 9.])
tensor([15., 12., 99.])


In [52]:
torch.matmul(int_32_tensor, int_32_tensor)

tensor(126.)

In [53]:
dot_product = 0
for j in range(len(int_32_tensor)):
    dot_product += int_32_tensor[j] * int_32_tensor[j]
dot_product

tensor(126.)

In [55]:
## Finding the min, max, mean, sum, etc(tensor aggregation)

In [56]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [57]:
torch.max(x) , torch.min(x)

(tensor(90), tensor(0))

In [59]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [61]:
x.argmin()

tensor(0)

In [62]:
x[0]

tensor(0)

# Reshaping, stacking, sequeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other(vstack) - side by side(hstack)
* Unsqueeze - add a '1' dimension to a target tensor
* Sequeeze - removes all '1' dimension from a target
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way


In [73]:
import torch

In [74]:
vector = torch.arange(1.0,10.0)
print(vector)
vector.shape

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])


torch.Size([9])

In [75]:
vector_reshaped = vector.reshape(1,9)
print(vector_reshaped)
vector_reshaped.shape

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])


torch.Size([1, 9])

In [76]:
vector_reshaped = vector.reshape(3,3)
print(vector_reshaped)
vector_reshaped.shape

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


torch.Size([3, 3])

In [89]:
new_tensor = vector.view(1,9)
new_tensor, new_tensor.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [90]:
# Changing variable in tensor will conclude changing values on vector
new_tensor[:,0] = 5
new_tensor, vector

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [102]:
new_tensor_stacked = torch.stack([new_tensor,new_tensor,new_tensor,new_tensor],dim = 2)
new_tensor_stacked, new_tensor_stacked.shape

(tensor([[[5., 5., 5., 5.],
          [2., 2., 2., 2.],
          [3., 3., 3., 3.],
          [4., 4., 4., 4.],
          [5., 5., 5., 5.],
          [6., 6., 6., 6.],
          [7., 7., 7., 7.],
          [8., 8., 8., 8.],
          [9., 9., 9., 9.]]]),
 torch.Size([1, 9, 4]))

In [101]:
new_tensor_stacked = torch.stack([new_tensor,new_tensor,new_tensor,new_tensor],dim = 1)
new_tensor_stacked, new_tensor_stacked.shape

(tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.],
          [5., 2., 3., 4., 5., 6., 7., 8., 9.],
          [5., 2., 3., 4., 5., 6., 7., 8., 9.],
          [5., 2., 3., 4., 5., 6., 7., 8., 9.]]]),
 torch.Size([1, 4, 9]))

In [108]:
y = torch.squeeze(new_tensor)
y, y.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [117]:
 y = torch.squeeze(new_tensor_stacked) # torch.Size([9, 4])) 1 dimension is sequezed
 y, y.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [118]:
y = torch.unsqueeze(y, dim =0) ##  torch.Size([1, 9, 4]))
y, y.shape

(tensor([[[5., 5., 5., 5.],
          [2., 2., 2., 2.],
          [3., 3., 3., 3.],
          [4., 4., 4., 4.],
          [5., 5., 5., 5.],
          [6., 6., 6., 6.],
          [7., 7., 7., 7.],
          [8., 8., 8., 8.],
          [9., 9., 9., 9.]]]),
 torch.Size([1, 9, 4]))

In [130]:
vector2 = torch.arange(1,10).reshape(1,3,3)
vector2

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [136]:
vector2[0,0][0]

tensor(1)

In [139]:
vector2[0,:,0]

tensor([1, 4, 7])

In [140]:
vector2[0,0,:]

tensor([1, 2, 3])

In [141]:
import numpy as np

In [144]:
array = np.arange(1,9,10)
type(array)

numpy.ndarray

In [146]:
tensor = torch.from_numpy(array)
tensor

tensor([1])

## Running tensors and PyTorch objects on the GPU


In [1]:
!nvidia-smi

Wed Oct 25 00:02:34 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [4]:
### 2. Check for GPU access with Pytorch
import torch
torch.cuda.is_available()

True

In [6]:
## how to make it device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [7]:
torch.device(device)

device(type='cuda')

In [8]:
## 3.Putting tensors on the GPU
tensor = torch.tensor([1,2,3], device = 'cpu')
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [10]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')